### ISSUE TITLE
Items outdated

### ISSUE THREAD

**Issue by cwkhawand** [Nenkai/GrowtopiaItemDatabase#2]
The items list is outdated. Missing new Halloween items.

Looking forward to an update,
Thanks Nenkai!

**Comment by zsmidori** [comment]
Yes pls lasted data @Nenkai

**Comment by NotDark** [comment]
i need it too!

**Comment by cwkhawand** [comment]
The update already passed, please update the DB

**Comment by Nenkai** [comment]
Halloween will be added on monthly/IOTM for November.
